[project]
name = "alltopdf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Callisto Casale", email = "callisto.casale@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fpdf2>=2.8.9",
    "pillow>=12.3.0",
    "python-docx>=1.2.0",
    "streamlit>=1.65.0",
]

[project.scripts]
alltopdf = "alltopdf:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
